version: '3'

services:

    server:
        build: ./server
        container_name: server
        ports:
            - 5000:5000
    
    client:
        build: ./client/pdf-masking-demo
        container_name: client
        tty: true
        ports:
            - 3000:3000
        environment:
            - REACT_APP_VAULT_ID=YOUR_VGS_VAULT_ID


